data:
    train_data: /opt/ml/input/data/dialogue/train.csv
    valid_data: /opt/ml/input/data/dialogue/valid.csv
    shuffle: True
    
model:
    model_name: klue/roberta-large
    saved_model: /opt/ml/input/poc/DTS
    # saved_model : /opt/ml/code/best_model/electra/electra_final_test.pt
    
train:
    train_mode: False
    seed: 42
    batch_size: 32
    epoch: 10
    lr: 3e-5
    second_lr : 5e-5
    num_workers : 4
    logging_step: 100
    patience : 2
    warmup_steps : 1000
    weight_decay: 0.01
    checkpoint : /opt/ml/input/poc
    marker_mode : TEM_punct

    T_0 : 100
    T_mult : 4
    eta_min : 1e-7
    


wandb:
    project_name: DTS
    entity: final-bora
    exp_name: 1 first_test for DTS_

huggingface :
  push_to_hub: True
  hub_private_repo: False
  push_to_hub_organization: yeombora
  hub_token: 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
  hub_model_id : Dialog_Topic_segmentation

