data:
    dataset_name: #cnn_dailymail
    dataset_config_name: #3.0.0
    train_file: /opt/ml/input/summarization_data/train/시사교육.json
    validation_file: /opt/ml/input/summarization_data/valid/시사교육.json
    overwrite_cache: False
    text_column:
    summary_column:
    output_dir: ./models/test
    checkpointing_steps:
    resume_from_checkpoint:

model:
    model_name_or_path: gogamza/kobart-base-v2
    use_slow_tokenizer: False

train:
    ignore_pad_token_for_loss:
    max_source_length: 512
    source_prefix: None
    preprocessing_num_workers:     
    max_target_length: 128
    val_max_target_length:
    max_length: 128
    num_beams:
    pad_to_max_length: False
    per_device_train_batch_size: 64
    per_device_eval_batch_size: 64
    learning_rate: 5e-5
    weight_decay: 0.1
    num_train_epochs: 1
    max_train_steps:
    gradient_accumulation_steps: 4
    lr_scheduler_type: linear
    num_warmup_steps: 0
    seed: 42
    model_type:
    with_tracking: True
    report_to: all

huggingface:
    push_to_hub: False
    hub_model_id:
    hub_token: 

wandb:
    wandb_mode: False
    entity: final_bora
    projcet_name: test
    exp_name: test
